version: '3'
services:
  www:
    depends_on:
      - db
    image: php:8.4.3-apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/var/www/html
    command: "/bin/sh -c 'docker-php-ext-install mysqli && apache2-foreground'"
    # the command is used to install the mysql lite and apache inside this container
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: 1
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      # the /docker-entrypoint-initdb.d is a directory in the container in the server
      # it is mapped to the ./db/colours.sql file in the local machine

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    ports:
      - 81:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306




